include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - public_member_api_docs
